
AVRDUDE = avrdude

#AVRDUDE_PROGRAMMER = -c usbasp
AVRDUDE_PROGRAMMER = -c arduino
AVRDUDE_BAUDRATE = -b 57600
AVRDUDE_PORT = -P /dev/ttyUSB0

AVRDUDE_PART = -p $(MCU)

AVRDUDE_FLAGS = $(AVRDUDE_PROGRAMMER) $(AVRDUDE_PART) $(AVRDUDE_BAUDRATE) $(AVRDUDE_PORT)
AVRDUDE_DEFAULT_SCK = -B 8
#AVRDUDE_128kHz_SCK = -B 16
